---
title: "Re-build train study with only evaluation probes"
author: "Fabien Jossaud, Florent Chuffart"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---


```{r echo=FALSE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=FALSE, results="hide")
source("../R/functions.R")
```

```{r loading_data}
df_filename_model = paste0("df_", gse_train, ".rds")
df_train = mreadRDS(df_filename_model)

df_filename_eval = paste0("df_", gse_eval, ".rds")
df_eval = mreadRDS(df_filename_eval)
```


```{r building_indexes}
idx_samples = rownames(df_train)

markers_start_model = grep("cg",colnames(df_train))[1]
idx_clinicals_model = colnames(df_train)[1:(markers_start_model-1)]
idx_cpg_model = colnames(df_train)[markers_start_model:ncol(df_train)]

markers_start_eval = grep("cg",colnames(df_eval))[1]
idx_clinicals_eval = colnames(df_eval)[1:(markers_start_eval-1)]
idx_cpg_eval = colnames(df_eval)[markers_start_eval:ncol(df_eval)]
```

```{r create df}
idx_probes = intersect(idx_cpg_eval, idx_cpg_model)
df = df_train[idx_samples,c(idx_clinicals_model,idx_probes)]
saveRDS(df,paste0("df_",gse_train,"given",gse_eval,".rds"))
```


# Session Information

```{r, results="verbatim"}
sessionInfo()
```
