---
title: "Descriptive statistics"
author: "Fabien Jossaud, Florent Chuffart"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---


```{r echo=FALSE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=FALSE, results="hide")
source("common.R")
```

```{r params}
source("params_default.R")
```


```{r loading_data}
if (gse != "dnamaging") {
  df_filename = paste0("~/projects/datashare/", gse, "/df_", gse, ".rds")
  df = mreadRDS(df_filename)
} else {
  df = dnamaging::df_dnamaging  
}

for (new_factoi in c("tobacco", "disease","gender")) {
  if (new_factoi %in% colnames(df)) {
    covariates = unique(c(covariates, new_factoi))  
  }  
}
```


```{r building_indexes}
idx_samples = rownames(df)
markers_start = grep("cg",colnames(df))[1]
idx_clinicals = colnames(df)[1:(markers_start-1)]
idx_cpg = colnames(df)[markers_start:ncol(df)]
```

## Explained variable

```{r}
layout(1, respect=TRUE)
hist(df[[y_key]], prob=TRUE, xlab=y_key, main=paste0(y_key, " distribution (", nrow(df), " obs.)")) 
lines(density(df[[y_key]]))
# Norm_Age = shapiro.test(df[[y_key]])
# text(60,0.03, paste0("SW Normality test p-val = ", round(Norm_Age$p.value,5)))
```


## Covariates

```{r, fig.height=4.5}
layout(matrix(1:2,1), respect=TRUE)
for (cov in covariates) {
  tmp_tab = table(df[[cov]], useNA="ifany")
  # tmp_col = 1:dim(tmp_tab)
  tmp_col = RColorBrewer::brewer.pal(n=max(3,dim(tmp_tab)), name = "Set1")
  tmp_x = barplot(tmp_tab, col=tmp_col, ylim=c(0,max(tmp_tab)*1.2), main=cov, las=2)
  text(tmp_x, tmp_tab+max(tmp_tab)*.1, labels=tmp_tab)

  f = paste0(y_key,"~",cov)
  beanplot::beanplot(formula(f), data=df, border=tmp_col, col=adjustcolor(c(1,1,1,1), alpha.f=.1), method="jitter", log="", ylab=y_key, xlab="", las=2, main=f)
  boxplot(formula(f), data=df, col=adjustcolor(tmp_col, alpha.f=.5), ylab=y_key, xlab="", las=2, main=f)
  beeswarm::beeswarm(formula(f), data=df, ylab=y_key, xlab="", col=tmp_col, las=2, main=f)  
}
```
```{r stock_info gse}
all_cofactors = c("disease","gender","tobacco")
info = c(
	name_gse = gse,
	platform = as.character(unique(df$platform)), 
	tissue = paste(unique(df$tissue),collapse="/"),
	n = nrow(df),
	cofactors = paste0(covariates,collapse="/")
)

distrib = list()
for (cov in covariates) {
  tmp_distrib = table(df[[cov]], useNA="always")
  names(tmp_distrib)[length(tmp_distrib)] = "NA"  
  if(length(distrib)==0){
  	distrib[[length(list)]] = tmp_distrib
  } else {
  	distrib[[length(list)+1]] = tmp_distrib
  }
}
names(distrib) = covariates

cofactors_distrib = c()
for (i in all_cofactors){
	if(i %in% covariates){
		tab = distrib[[i]]
		cofactors_distrib = c(cofactors_distrib, paste0(stringr::str_c(names(tab),tab,sep="="),collapse=" / "))
	} else { cofactors_distrib = c(cofactors_distrib,paste0("No ",i," distribution in this GSE")) }
}
names(cofactors_distrib) = all_cofactors
info = c(info,cofactors_distrib)	

saveRDS(info,paste0("info_desc_",gse,".rds"))


```

