---
title: "Descriptive Statistics"
author: "Fabien Jossaud, Florent Chuffart"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---


```{r echo=FALSE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=FALSE, results="hide")
start_time = Sys.time()
source("common.R")
```

```{r params}
source("params_default.R")
```


```{r loading_data}
if (gse != "dnamaging") {
  df_filename = paste0("./datashare/", gse, "/df_", gse, ".rds")
  df = mreadRDS(df_filename)
} else {
  df = dnamaging::df_dnamaging  
}

covariates = intersect(c("tobacco", "disease", "gender"), colnames(df))
```


```{r building_indexes}
idx_samples = rownames(df)
markers_start = grep("cg",colnames(df))[1]
idx_clinicals = colnames(df)[1:(markers_start-1)]
idx_cpg = colnames(df)[markers_start:ncol(df)]
n = nrow(df)
tissue = paste(unique(df$tissue),collapse="/")
```

# Explained variable

```{r}
if (y_key %in% colnames(df)) {
  layout(1, respect=TRUE)
  hist(df[[y_key]], prob=TRUE, xlab=y_key, main=paste0(y_key, " distribution (", nrow(df), " obs.)")) 
  lines(density(df[[y_key]]))
}
# Norm_Age = shapiro.test(df[[y_key]])
# text(60,0.03, paste0("SW Normality test p-val = ", round(Norm_Age$p.value,5)))
```


# Covariates

```{r, fig.height=4.5}
for (cov in covariates) {
  layout(matrix(1:2,1), respect=TRUE)
  tmp_tab = table(df[[cov]], useNA="ifany")
  # tmp_col = 1:dim(tmp_tab)
  tmp_col = RColorBrewer::brewer.pal(n=max(3,dim(tmp_tab)), name = "Set1")
  tmp_x = barplot(tmp_tab, col=tmp_col, ylim=c(0,max(tmp_tab)*1.2), main=cov, las=2)
  text(tmp_x, tmp_tab+max(tmp_tab)*.1, labels=tmp_tab)

  if (y_key %in% colnames(df)) {
    f = paste0(y_key,"~",cov)
    beanplot::beanplot(formula(f), data=df, border=tmp_col, col=adjustcolor(c(1,1,1,1), alpha.f=.1), method="jitter", log="", ylab=y_key, xlab="", las=2, main=f)
    boxplot(formula(f), data=df, col=adjustcolor(tmp_col, alpha.f=.5), ylab=y_key, xlab="", las=2, main=f)
    beeswarm::beeswarm(formula(f), data=df, ylab=y_key, xlab="", col=tmp_col, las=2, main=f)  
  }
}
```


# Missing values

**TODO**, adding description, what appends there?

```{r missing values, results="verbatim"}
if (sum(is.na(df[,idx_cpg]))>0) {
  # Looking how much got more than 5% missing values
  # apply_func = epimedtools::monitored_apply
  if (! exists("apply_func")) {apply_func = apply}
  prop_na_col =  apply_func(is.na(df[idx_samples,idx_cpg]), 2, sum) / nrow(df)
  sum(prop_na_col>=1)
  idx_cpg = names(prop_na_col)[prop_na_col<1]
  print(paste0("#probes removed (all NA): ", sum(prop_na_col>=.05)))

  prop_na_row =  apply_func(is.na(df[idx_samples,idx_cpg]), 1, sum) / ncol(df)
  idx_samples = names(prop_na_row)[prop_na_row<.05]
  prop_na_col =  apply_func(is.na(df[idx_samples,idx_cpg]), 2, sum) / nrow(df)
  sum(prop_na_col>=.05)
  idx_cpg = names(prop_na_col)[prop_na_col<.05]

  print(paste0("#samples removed: ", sum(prop_na_row>=.05)))
  print(paste0("#probes removed: ", sum(prop_na_col>=.05)))

  df = df[idx_samples, c(idx_clinicals, idx_cpg)]

  ## KNN - We use the function impute.knn of the package impute to replace remaining missing values with KNN method. 
  dknn = as.matrix(df[,idx_cpg])
  dknnf = impute::impute.knn(dknn, k=10, maxp=5000, rng.seed=1)
  dknn = dknnf$data
  head(dknn[,1:6])
  df = cbind(df[idx_samples,idx_clinicals],dknn[idx_samples,idx_cpg])
} else {
  print("# No NA.") 
}
```

# sd distribution before filtering


```{r filter_sd1, fig.height=4.5}
print("Filtering probes according to sd")
d = t(as.matrix(df[,idx_cpg]))
sd_thresh = 0.05
sds = apply(d, 1, sd)
sum(is.na(sds))
sds = sds[!is.na(sds)]

idx_probes_sd = names(sds)[sds > sd_thresh]
length(idx_probes_sd)
length(sds)

layout(matrix(1:2,1), respect=TRUE)
plot(density(sds), main=paste("sd distribution"))
abline(v=sd_thresh)
plot(density(d                ), main=paste("Methtylation distribution"), lty=2)
den = density(d[idx_probes_sd,])
lines(den$x, den$n / (nrow(d)*ncol(d)) * den$y, col=2, lty=1)
den = density(d[setdiff(rownames(d),idx_probes_sd),])
lines(den$x, den$n / (nrow(d)*ncol(d)) * den$y, col=4, lty=1)
legend("topright", c("all", paste0("sd>", sd_thresh), paste0("sd<=", sd_thresh)), col=c(1,2,4), lty=c(2,1,1))
```


# Outliers (PCA)

**TODO**, adding description, what appends there?

```{r acp, results="verbatim"}
padj = 0
covariate = covariates[1]
df[,covariate] = as.factor(df[,covariate])
levls = levels(df[,covariate])
it=1
while(sum(padj < 0.2) != 0) {
  print(paste0("******* iteration #", it, "..."))
  it = it+1
  mat = as.matrix(df[idx_samples, idx_cpg])
  pca = prcomp(mat, scale=FALSE)
  v = pca$sdev * pca$sdev
  p = v / sum(v) * 100
  layout(matrix(1:6,2), respect=TRUE)
  # layout(matrix(1:2,1), respect=TRUE)
  barplot(p, ylab="% of variance explained", xlab="components")
  for (i in 1:5) {
    j = i+1
    plot(pca$x[,i], pca$x[,j], 
    	xlab=paste0("PC", i, "(", signif(p[i], 3), "%)"), 
    	ylab=paste0("PC", j, "(", signif(p[j], 3), "%)"), 
    	col=as.numeric(df[idx_samples,covariate]),
    	pch=16)  
    legend(x="topright", legend=levls, col=1:length(levls), lty = 1, title=covariate)
    # scale_factor = min(abs(c(min(c(pca$x[,i], pca$x[,j])), max(c(pca$x[,i], pca$x[,j])))))
    # scale_factor = min(abs(c(max(min(pca$x[,i]), min(pca$x[,j])), min(max(pca$x[,i]), max(pca$x[,j])))))
    # arrows(0,0,pca$rotation[,i]*scale_factor, pca$rotation[,j]*scale_factor, col="grey")
    # text(pca$rotation[,i]*scale_factor, pca$rotation[,j]*scale_factor, rownames(pca$rotation))
  }
  print(paste0("  removing..."))
  head(pca$x[,1:2])
  mean = mean(pca$x[,1])
  sd = sd(pca$x[,1])
  pval = pnorm(abs(pca$x[,1]), mean, sd, lower.tail=FALSE)
  padj = p.adjust(pval, method="BH")
  sum(padj <= 0.2)
  range(padj)  
  idx_samples = names(padj)[padj > 0.2]
  print(paste0("  #sample removed: ", nrow(df) - length(idx_samples)))
  df = df[idx_samples,]
}
print(paste0("end of iterations."))

```







# sd distribution after filtering


 

```{r filter_sd2, fig.height=4.5}
print("Filtering probes according to sd")
d = t(as.matrix(df[,idx_cpg]))
sd_thresh = 0.05
sds = apply(d, 1, sd)
sum(is.na(sds))
sds = sds[!is.na(sds)]
# plot(density(sds))
# abline(v=sd_thresh)


idx_probes_sd = names(sds)[sds > sd_thresh]
# idx_probes_sd
length(idx_probes_sd)
length(sds)

layout(matrix(1:2,1), respect=TRUE)
plot(density(sds), main=paste("sd distribution"))
abline(v=sd_thresh)
plot(density(d                ), main=paste("Methtylation distribution"), lty=2)
den = density(d[idx_probes_sd,])
lines(den$x, den$n / (nrow(d)*ncol(d)) * den$y, col=2, lty=1)
den = density(d[setdiff(rownames(d),idx_probes_sd),])
lines(den$x, den$n / (nrow(d)*ncol(d)) * den$y, col=4, lty=1)
legend("topright", c("all", paste0("sd>", sd_thresh), paste0("sd<=", sd_thresh)), col=c(1,2,4), lty=c(2,1,1))
```

# Save


```{r export preprocessed df, results="verbatim", echo=TRUE}
dim(df)
saveRDS(df, paste0("df_preproc_",gse,".rds"))
```





```{r}
######## Metadata ##############
all_cofactors = c("disease","gender","tobacco")
distrib = list()
for (cov in covariates) {
  tmp_distrib = table(df[[cov]], useNA="always")
  names(tmp_distrib)[length(tmp_distrib)] = "NA"  
  distrib[[length(distrib)+1]] = tmp_distrib
}
names(distrib) = covariates

cofactors_distrib = c()
for (i in all_cofactors){
	if(i %in% covariates){
		tab = distrib[[i]]
		cofactors_distrib = c(cofactors_distrib, paste0(stringr::str_c(names(tab),tab,sep="="),collapse=" / "))
	} else { cofactors_distrib = c(cofactors_distrib,paste0("No ",i," distribution in this GSE")) }
}
names(cofactors_distrib) = all_cofactors
```

```{r}
stop_time = Sys.time()
info = list(
  exec_time = round(difftime(stop_time, start_time, units="mins"),1),
	tissue = tissue,
	n = n,
	n_preproc = nrow(df),
	cofactors = paste0(covariates,collapse="/")
)

saveRDS(info, paste0("info_desc_",gse,".rds"))
```

# Session Information

```{r, results="verbatim"}
sessionInfo()
```

