---
title: "EWAS"
author: "Fabien Jossaud, Florent Chuffart"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---



```{r echo=FALSE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=FALSE, results="hide")
start_time = Sys.time()
source("common.R")
```

```{r params_default, echo=FALSE}
source("params_default.R")
if (!exists("seed")) seed = 1
if (!exists("scenario")) scenario = "A"
if (!exists("dist_nn")) dist_nn = 0

```

```{r load data and build indexes, echo=FALSE}
print("Loading data")
df = mreadRDS(paste0("df_preproc_",gse,".rds"))
for (new_factoi in c("tobacco", "disease")) {
  if (new_factoi %in% colnames(df)) {
    covariates = unique(c(covariates, new_factoi))  
  }  
}

idx_samples = rownames(df)
markers_start = grep("cg",colnames(df))[1]
idx_clinicals = colnames(df)[1:(markers_start-1)]
idx_cpg = colnames(df)[markers_start:ncol(df)]
```

## Model

```{r}
if (scenario=="A") {
  confounders = NULL  
} else if (scenario=="B") {
  confounders = "gender01"
} else if (scenario=="C") {
  confounders = c(
    # "B"      ,
    "NK"     ,
    "CD4T"   ,
    "CD8T"   ,
    "Gran"   ,
    "Mono"   ,
    "Neutro" ,
    "Eosino"
  )
} else if (scenario=="D") {
  confounders = c(
    "gender01"      ,
    "NK"     ,
    "CD4T"   ,
    "CD8T"   ,
    "Gran"   ,
    "Mono"   ,
    "Neutro" ,
    "Eosino"
  )
} else {
  confounders = NULL  
}
```

`r paste0("~", paste0(c(y_key, confounders), collapse="+"))`


## Training and test sets 

```{r parameters, echo=TRUE, results="verbatim"}
if (nrow(df) - nb_train<100) {
  nb_train = ceiling(nrow(df)/2)
}
print(paste0("Use ", nb_train, " observations for training."))
set.seed(seed)
idx_train = sample(rownames(df), nb_train)
idx_test = setdiff(rownames(df), idx_train)      
```

## Filtering probes using EWAS 


```{r ewas}
if (nbewasprobes>0) {
  print("filtering EWAS top probes")
  x = mget_full_cpg_matrix(gse, idx_train, idx_cpg)
  cpg_matrix = t(x)
  if (!is.null(confounders)) {
    design_matrix <- model.matrix(formula(paste0("~", y_key, "+", paste0(confounders, collapse="+"))), df[idx_train,idx_clinicals])    
  } else {
    design_matrix <- model.matrix(formula(paste0("~", y_key)), df[idx_train,idx_clinicals])    
  }
  dim(design_matrix)
  dim(cpg_matrix)
  fit = mlimma_lmFit(cpg_matrix, design_matrix)
  fit = limma::eBayes(fit) # compute moderated t-statistics, moderated F-statistic, and log-odds of differential expression by empirical Bayes moderation of the standard errors towards a global value
  # head(fit$p.value)
  idx_cpg_oi = rownames(fit$p.value)[rank(fit$p.value[,2]) <= nbewasprobes]
  layout(1, respect=TRUE)
  plot(fit$coefficients[,2], -log10(fit$p.value[,2]), col=(rownames(fit$p.value) %in% idx_cpg_oi)+1, pch=".", main=paste0(nbewasprobes, " probes"))

  litterature_models = readRDS("litterature_models.rds")  
  idx_cpg_litt = unique(unlist(lapply(lapply(litterature_models, "[[", "coeff"), "[[", "probes")))  

  idx_cpg = intersect(idx_cpg, c(idx_cpg_oi, idx_cpg_litt))

  dim(df)
  df = df[,c(idx_clinicals, idx_cpg)]
  dim(df)


  # df_dnamaging = df
  # colnames(df_dnamaging)[2] = "age"
  # head(df_dnamaging[,1:20])
  # save(df_dnamaging, file='./dnamaging/data/df_dnamaging.RData' , compress='xz')
} else {
  # Nothing to do for idx_cpg
}
```
```{r nn_computing}
if(dist_nn != 0){
  
  df_preproc = mreadRDS(preproc_filename)

  foo = mreadRDS(paste0("../../datashare/",gse,"/study_",gse,".rds"))
  platform = foo$platform
	
  foo = read.table("~/projects/datashare/hg38.chrom.sizes")[1:24,]

  platform = platform[order(platform$chr,platform$pos),]
  platform$pos_prev_nn = c(NA,platform$pos[-length(platform$pos)])
  platform$pos_next_nn =  c(platform$pos[-1],NA)
  platform$dist_prev_nn = platform$pos - platform$pos_prev_nn
  platform$dist_next_nn = platform$pos_next_nn - platform$pos
  platform[is.na(platform$dist_prev_nn) | platform$dist_prev_nn < 0,]$dist_prev_nn = max(foo[,2])
  platform[is.na(platform$dist_next_nn) | platform$dist_next_nn < 0,]$dist_next_nn = max(foo[,2])
  platform$is_kept = FALSE
  platform[idx_cpg,]$is_kept = TRUE
  new_count = sum(platform$is_kept,na.rm = TRUE)
  old_count = new_count -1 
  while(old_count < new_count) {
	  old_count = new_count
	  platform$is_kept = platform$is_kept | (platform$dist_prev_nn <= dist_nn & c(FALSE,platform$is_kept[-length(platform$is_kept)] %in%TRUE))
	  print(sum(platform$is_kept,na.rm = TRUE))
	  platform$is_kept = platform$is_kept | (platform$dist_next_nn <= dist_nn & c(platform$is_kept[-1],FALSE) %in%TRUE)
	  new_count = sum(platform$is_kept,na.rm = TRUE)
  }

  idx_kept = rownames(platform)[platform$is_kept]  
  idx_kept = idx_kept[idx_kept %in% colnames(df_preproc)]
  df = df_preproc[,c(idx_clinicals,idx_kept)]

}
```

```{r save_ewas}
saveRDS(df, paste0("df_r0_ewas", nbewasprobes, "_nn", dist_nn, "_", gse, ".rds"))
```


# Process Information 

```{r}
stop_time = Sys.time()
info = list(
  exec_time = round(difftime(stop_time, start_time, units="mins"),1)
)

saveRDS(info, paste0("info_ewas", nbewasprobes, "_nn", dist_nn, "_", gse, ".rds"))
```

# Session Information

```{r, results="verbatim"}
sessionInfo()
```


