---
title: "Post processing `predimethaging`"
author: "Florent Chuffart"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---

```{r echo=FALSE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=9, eval=TRUE, echo=FALSE, results="hide")
source("common.R")
```

```{r}
predimethaging = function()  {
  # layout(1, respect=TRUE)
  layout(matrix(c(
    1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,
    1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,
    1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,
    1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,
    1,1,1,1,1,1,1,1,3,3,3,3,3,3,3,3,
    1,1,1,1,1,1,1,1,3,3,3,3,3,3,3,3,
    1,1,1,1,1,1,1,1,3,3,3,3,3,3,3,3,
    1,1,1,1,1,1,1,1,3,3,3,3,3,3,3,3,
    4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,
    4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,
    4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,
    4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,
    4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,
    4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,
    4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,
    4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,
    6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6, 
    6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6, 
    6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6, 
    6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6, 
    6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6, 
    6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6, 
    6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6, 
    6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6, 
    NULL), 24, byrow=TRUE), respect=TRUE)
   par(mar=c(5.1, 4.1, .1, .1))
 # beanplot::beanplot(exp_grp$age ~ paste0(exp_grp$gender, " (", table(exp_grp$gender)[exp_grp$gender], " individuals)"), what=c(1,1,1,0), col="grey", main=paste0("age distribution (", nrow(exp_grp), " individuals)"), ylab="age (years)")
  ag.f = table(exp_grp[exp_grp$gender=="F",]$age)
  ag.m = table(exp_grp[exp_grp$gender=="M",]$age)
  xlim = c(-max(ag.f), max(ag.m))
  b = barplot(ag.m, horiz=T, xlim=xlim, col=4, yaxt="n", xaxt="n", ylab="age (years)", 
              # main=paste0("age distribution (", nrow(exp_grp), " individuals)")
              )  # plot left
  barplot(-ag.f, horiz=T, add=TRUE, col=2, xaxt="n", yaxt="n")  # plot right
  polygon(c(-1.2,1.2,1.2,-1.2), c(min(b)-1, min(b)-1, max(b)+1, max(b)+1), border=NA, col=adjustcolor("white", alpha.f=.66))
  text(0, b, sort(unique(exp_grp$age)))
  axis(1, at=((-2):4)*10, labels=c((2:1), 0:4)*10)
  mtext(c(paste0("F (", table(exp_grp$gender)["F"], " individuals)"), paste0("M (", table(exp_grp$gender)["M"], " individuals)"))
    , 1, 2.5, at=c(-10,20), las=1)

  put_a_letter("a")

  
  # col=1
  # plot(d, col=0, xlab="Methylation proportion", main="")
  # lines(d_m, col=adjustcolor(2, alpha.f=.8), lwd=2)
  # lines(d_f, col=adjustcolor(4, alpha.f=.8), lwd=2)
  # # lines(d,     col=adjustcolor(1, alpha.f=.4), lwd=3)
  # legend(title="Gender", "topleft", lwd=3, col=c(4, 2), lty=1, c(
  #   paste0(sum(exp_grp$gender=="M"), " Males"),
  #   paste0(sum(exp_grp$gender=="F"), " Females")
  #   )
  # )


  # par(mar=c(5.1, 4.1, 4.1, 2.1))
  # par(mar=c(0, 4.1, .1, .1))
  # lwd = 2
  # plot(d, col="grey", xlab="Methylation proportion", main="", lwd=lwd, xaxt="n")
  # lines(d_Islan$x, d_Islan$y * length(idx_Islan)/nrow(pfepichg38), col=adjustcolor(colpals_cpgdensity[1], alpha.f=.8), lwd=lwd)
  # lines(d_Shore$x, d_Shore$y * length(idx_Shore)/nrow(pfepichg38), col=adjustcolor(colpals_cpgdensity[2], alpha.f=.8), lwd=lwd)
  # lines(d_Shelf$x, d_Shelf$y * length(idx_Shelf)/nrow(pfepichg38), col=adjustcolor(colpals_cpgdensity[3], alpha.f=.8), lwd=lwd)
  # lines(d_OpenS$x, d_OpenS$y * length(idx_OpenS)/nrow(pfepichg38), col=adjustcolor(colpals_cpgdensity[4], alpha.f=.8), lwd=lwd)
  # # lines(d,     col=adjustcolor(1, alpha.f=.4), lwd=3)
  # legend(bty="n", "topleft", lwd=lwd, col=c("grey", colpals_cpgdensity), lty=1, c(
  #     paste0("All"     , " (", nrow(pfepichg38) , " probes)"),
  #     paste0("Island"  , " (", length(idx_Islan), " probes)"),
  #     paste0("Shore"   , " (", length(idx_Shore), " probes)"),
  #     paste0("Shelf"   , " (", length(idx_Shelf), " probes)"),
  #     paste0("OpenSea" , " (", length(idx_OpenS), " probes)")
  #   )
  # )
  # put_a_letter("b")


  par(mar=c(0, 4.1, 0, .1))
  lwd = 2
  colpals_yngold=c("purple", "darkgreen")
  plot(d, col=0, xlab="Methylation proportion", main="", xaxt="n", ylim=c(0,4.5))
  lines(d_yng, col=adjustcolor(colpals_yngold[1], alpha.f=.8), lwd=lwd)
  lines(d_old, col=adjustcolor(colpals_yngold[2], alpha.f=.8), lwd=lwd)
  # lines(d,     col=adjustcolor(1, alpha.f=.4), lwd=3)
  legend(bty="n", "topleft", lwd=lwd, col=colpals_yngold, lty=1, c(
    paste0(sum(exp_grp$qtage==levels(exp_grp$qtage)[1]), " youngest individuals"),
    paste0(sum(exp_grp$qtage==rev(levels(exp_grp$qtage))[1]), " oldest individuals")
    )
  )
  put_a_letter("b")

  par(mar=c(5.1, 4.1, 0, .1))
  plot(d_yng$x, d_old$y - d_yng$y, col=0, xlab="Methylation proportion", main="", type="l", lwd=lwd, yaxt="n", ylim=c(-.35,.12), ylab=expression(paste(Delta, " Density        ")))
  axis(2, at=c(-.2, 0), labels=c(-.2, 0))
  abline(h=0, col="grey")

  x = d_old$x
  y_yng = y_old = d_old$y - d_yng$y
  y_old[y_old<0] = 0
  y_yng[y_yng>0] = 0
  polygon(x, y_old, col=colpals_yngold[2], border=0)
  polygon(x, y_yng, col=colpals_yngold[1], border=0)
  put_a_letter("c")

  par(mar=c(5.1, 4.1, 4.1, 2.1))




# predimethstatsfig = function() {
#   layout(matrix(1:2, 1), respect=TRUE)
  par(mar=c(0, 0, 0, 0))
  img = png::readPNG(paste0("../misc/wf.png"))
  plot(NA, NA, xlim=0:1, ylim=0:1, axes=FALSE, main=paste0(""), xlab="", ylab="")
  addImg(img, x=.5,y=.5,width=1.9)
  par(mar=c(5.1, 4.1, 4.1, 2.1))  
  put_a_letter("d")


  s = mreadRDS(study_filename)
  null_rmse = sd(s$exp_grp$age)

  x = c(0:runmax)
  r2_bs = c()
  rmse_bs = c()
  nb_pb_bs = c()
  for (run in 0:runmax){
    tmp_info_model_bs = mreadRDS(paste0("info_model_r",run,"_",gse,"_modelcalllm_meth~age_ewas", newas, "_nn", neighb, ".rds"))
    tmp_nb_pb_bs = tmp_info_model_bs$gender.bootstrap.nb_probes_mod
    tmp_rmse_bs = tmp_info_model_bs$gender.bootstrap.RMSE
    tmp_r2_bs = tmp_info_model_bs$gender.bootstrap.R2
    rmse_bs = c(rmse_bs,tmp_rmse_bs)
    r2_bs = c(r2_bs,tmp_r2_bs)	
    nb_pb_bs = c(nb_pb_bs, tmp_nb_pb_bs)
  }
	## add extra space to right margin of plot within frame
	par(mar=c(5.1, 4.1, 4.1, 5.1))
	## Plot first set of data and draw its axis
	plot(x, rmse_bs, xlab="iterations", ylab="RMSE", 
	     type="b", ylim=c(0,max(null_rmse, rmse_bs)), lty=1, col="black", main="")
	# axis(2, ylim=c(0,null_rmse+1),col="black",las=1)  ## las=1 makes horizontal labels
  abline(h=null_rmse, col = "black", lty=2)
	# abline(v=10, col="black",lty = 2)

	## Allow a second plot on the same graph
	par(new=TRUE)

	## Plot the second plot and put axis scale on right
	cum_nb = cumsum(nb_pb_bs)

  plot(x, cum_nb,  xlab="", ylab="", 
	    axes=FALSE, type="b", col="red", lty=1, ylim=c(0, max(cum_nb)))
	## a little farther out (line=4) to make room for labels
	mtext("number of cumulative probes", side=4, col="red", line=4) 
	axis(4, ylim=c(0,max(cum_nb)+200,10), col="red",col.axis="red",las=1, lwd=0, lwd.ticks=1)

	legend("bottomright",
	  legend=c("null model RMSE", "RMSE at each iteration", "cumulative number of probes"), 
		col=c("black", "black", "red"), lty = c(2, 1, 1), pch= c(1,1,NA), cex=1)
  put_a_letter("e")
	par(mar=c(5.1, 4.1, 4.1, 2.1))



  par(mar=c(0, 0, 0, 0))
  img = png::readPNG(upset_signature_pngfile)
  plot(NA, NA, xlim=0:1, ylim=0:1, axes=FALSE, main=paste0(""), xlab="", ylab="")
  addImg(img, x=.5,y=.5,width=0.9)
  put_a_letter("f")
  par(mar=c(5.1, 4.1, 4.1, 2.1))  






}
upset_signature_pngfile = paste0("upset_signature_", gse, ".png")
png(upset_signature_pngfile, width=800, height=500, res=100)
UpSetR::upset(ewas[,names(signatures)], mb.ratio = c(0.7, 0.3), nsets=6)
dev.off()

predimethaging()
pdf(paste0("fig_", gse, "_predimethaging.pdf"), width=8, height=12)
# # png("predimethagingfig.png", width=800, height=600)
predimethaging()
dev.off()
```

```{r echo=TRUE, results="verbatim"}
exp_grp$age
```





