---
title: "Build predictive model using RF"
author: "Fabien Jossaud"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---

```{r echo=FALSE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=FALSE, results="hide")
start_time = Sys.time()
source("common.R")
```



```{r params}
nbewasprobes = 10000
gse = "trainGBMtest"
y_key = "meth_class"
```

```{r ewas creation}
rmarkdown::render('03_ewas.Rmd',output_file=paste0('03_ewas', nbewasprobes,'_',gse,'_',y_key, '.html'))
y_key = "meth_class"
```

```{r rf}
df = readRDS(paste0("df_r0_ewas", nbewasprobes, "_", gse,".rds"))
markers_start = grep("cg",colnames(df))[1]
idx_cpg = colnames(df)[markers_start:ncol(df)]
x <- df[,idx_cpg]
y <- df[,y_key]
dataset = cbind(x,y)

control <- caret::trainControl(method='repeatedcv', 
	                        number=10, 
	                        repeats=3)
set.seed(123)
#Number randomely variable selected is mtry
mtry <- sqrt(ncol(x))
tunegrid <- expand.grid(.mtry=mtry)
rf_default <- caret::train(y~., 
    	                  data=dataset, 
        	              method='rf', 
        	              metric='Accuracy', 
        	              tuneGrid=tunegrid, 
        	              trControl=control)
print(rf_default)
saveRDS(rf_default,paste0("rf_model",nbewasprobes,"_",y_key,".rds"))
```

# Process Information 

```{r}
stop_time = Sys.time()
info = list(
  exec_time = round(difftime(stop_time, start_time, units="mins"),1)
)
saveRDS(info, paste0("info_grimec_model_", nbewasprobes, "_", gse, ".rds"))
```

```{r echo=TRUE, results="verbatim"}
info
```

# Session Information

```{r, results="verbatim"}
sessionInfo()
```
