,---
title: "Grimec prediction"
author: "Jossaud Fabien"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---



```{r, echo=FALSE, eval=TRUE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=FALSE, results="hide", warning=FALSE)
```


```{r params and data}
source("common.R")

betas = readRDS("models_r0_ewas3000_GSE40279_grimec.rds") # make creation of this model ! 

betas_litt = readRDS("litterature_models.rds")
df_grim = readRDS("../../datashare/GRIMEC001/df_GRIMEC001.rds")
df_grim=t(df_grim)
```

```{r preprocessing}

gse = "train_age_grimec" #GSE special for Grimec with only 1000 individuals in GSE90496 
rmarkdown::render('02_stat_preproc.Rmd',output_file=paste0('02_stat_preproc_',gse,'.html')); # Start preprocessing
markers_start = grep("cg",colnames(df))[1]
idx_clinicals = colnames(df)[1:(markers_start-1)]
idx_cpg = colnames(df)[markers_start:ncol(df)]
idx_cpg = idx_cpg[idx_cpg %in% colnames(df_grim)] # Keeping only cpg common with Grimec
df = df[,c(idx_clinicals,idx_cpg)]
saveRDS(df, paste0("df_preproc_",gse,".rds") # Save preproc dataset with common cpg between grimec and 90496
```

# Age prediction 

```{r model}
gse = "train_age_grimec"
nbewasprobes=10000 
rmarkdown::render('03_ewas.Rmd',output_file=paste0('03_ewas', nbewasprobes,'_',gse, '.html'))
run=0 
rmarkdown::render('04_model.Rmd', output_file=paste0('04_model_r',run,'_ewas',nbewasprobes,'_',gse,'.html'))
```

```{r age 90496}
betas9 = readRDS("models_r0_ewas10000_train_age_grimec.rds")

inter_gd = betas9[[2]]$Intercept 
coeff_gd = betas9[[2]]$coeff
probes_gd = df_grim[,colnames(df_grim) %in% rownames(coeff_gd)]

age_gd = inter_gd + probes_gd %*% coeff_gd$beta

```

```{r age 40279}

inter_self = betas[[2]]$Intercept 
coeff_self = betas[[2]]$coeff
probes_self = df_grim[,colnames(df_grim) %in% rownames(coeff_self)]

age_self = inter_self + probes_self %*% coeff_self$beta

```

```{r age Hannum}

inter_hannum = betas_litt$hannum_model_mc$Intercept 
coeff_hannum = betas_litt$hannum_model_mc$coeff[rownames(betas_litt$hannum_model_mc$coeff) %in% colnames(df_grim),]
probes_hannum = df_grim[,colnames(df_grim) %in% rownames(coeff_hannum)]

age_hannum = inter_hannum + probes_hannum %*% coeff_hannum$beta

```

```{r age Horvath}

inter_horvath = betas_litt$horvath_model_mc$Intercept 
coeff_horvath = betas_litt$horvath_model_mc$coeff[rownames(betas_litt$horvath_model_mc$coeff) %in% colnames(df_grim),]
probes_horvath = df_grim[,colnames(df_grim) %in% rownames(coeff_horvath)]

age_horvath = inter_horvath + probes_horvath %*% coeff_horvath$beta

```

```{r concatenate ages predictions}

ages = cbind(age_gd,age_self,age_hannum,age_horvath)
colnames(ages) = c("train_gbm","Self","Hannum","Horvath")
ages = round(ages,digits=0)

saveRDS(ages,"pred_ages.rds")

```
# Different class predictions (class,family,super_f)

```{r class prediction}

gse = "trainGBMgrimec"
nbewasprobes = 10000
y_key = "meth_class"
rmarkdown::render('03_ewas.Rmd',output_file=paste0('03_ewas', nbewasprobes,'_',gse,'_',y_key, '.html'))

#Grid search and RF

df = mreadRDS(paste0("df_r0_ewas", nbewasprobes, "_", gse, ".rds"))
markers_start = grep("cg",colnames(df))[1]
idx_cpg = colnames(df)[markers_start:ncol(df)]
x <- df[,idx_cpg]
y <- df[,y_key]
dataset = cbind(x,y)

control <- trainControl(method='repeatedcv', 
                        number=10, 
                        repeats=3)
#Metric compare model is Accuracy
metric <- "Accuracy"
set.seed(123)
#Number randomely variable selected is mtry
mtry <- sqrt(ncol(x))
tunegrid <- expand.grid(.mtry=mtry)
rf_default <- train(y~., 
                      data=dataset, 
                      method='rf', 
                      metric='Accuracy', 
                      tuneGrid=tunegrid, 
                      trControl=control)
print(rf_default)
saveRDS(rf_default,"rf_model_pred_disease.rds")

disease =  predict(rf_default, newdata = df_grim, nodes = TRUE)
names(disease) = rownames(df_grim)
saveRDS(disease,"pred_disease.rds")

```

```{r family prediction}

nbewasprobes = 10000
y_key = "meth_family"
rmarkdown::render('03_ewas.Rmd',output_file=paste0('03_ewas', nbewasprobes,'_',gse,'_',y_key, '.html'))

df = mreadRDS(paste0("df_r0_ewas", nbewasprobes, "_", gse, ".rds"))
markers_start = grep("cg",colnames(df))[1]
idx_cpg = colnames(df)[markers_start:ncol(df)]
x <- df[,idx_cpg]
y <- df[,y_key]
dataset = cbind(x,y)

control <- caret::trainControl(method='repeatedcv', 
                        number=10, 
                        repeats=3)
#Metric compare model is Accuracy
metric <- "Accuracy"
set.seed(123)
#Number randomely variable selected is mtry
mtry <- sqrt(ncol(x))
tunegrid <- expand.grid(.mtry=mtry)
rf_default <- caret::train(y~., 
                      data=dataset, 
                      method='rf', 
                      metric='Accuracy', 
                      tuneGrid=tunegrid, 
                      trControl=control)
print(rf_default)
saveRDS(rf_default,"rf_model_pred_family.rds")
if(nrow(df_grim) > 100000){
	df_grim = t(df_grim)
}
family =  predict(rf_default, newdata = df_grim, nodes = TRUE)
names(family) = rownames(df_grim)
saveRDS(family,"pred_family.rds")

```

```{r super family prediction}

gse = "trainGBMgrimec"
nbewasprobes = 10000
y_key = "super_family"
rmarkdown::render('03_ewas.Rmd',output_file=paste0('03_ewas', nbewasprobes,'_',gse,'_',y_key, '.html'))

df = readRDS(paste0("df_r0_ewas", nbewasprobes, "_", gse, ".rds"))
markers_start = grep("cg",colnames(df))[1]
idx_cpg = colnames(df)[markers_start:ncol(df)]
x <- df[,idx_cpg]
y <- df[,y_key]
dataset = cbind(x,y)

control <- caret::trainControl(method='repeatedcv', 
                        number=10, 
                        repeats=3)
#Metric compare model is Accuracy
metric <- "Accuracy"
set.seed(123)
#Number randomely variable selected is mtry
mtry <- sqrt(ncol(x))
tunegrid <- expand.grid(.mtry=mtry)
rf_default_super_f <- caret::train(y~., 
                      data=dataset, 
                      method='rf', 
                      metric='Accuracy', 
                      tuneGrid=tunegrid, 
                      trControl=control)
print(rf_default_super_f)
saveRDS(rf_default_super_f,"rf_model_pred_super_f.rds")

if(nrow(df_grim) > 100000){
	df_grim = t(df_grim)
}
super_f =  predict(rf_default_super_f, newdata = df_grim, nodes = TRUE)
names(super_f) = rownames(df_grim)
saveRDS(super_f,"pred_super_f.rds")

```

# Predict gender 

```{r filter GSE40279 probes}

gse = "trainGendergrimec"
df_gender = readRDS("df_preproc_GSE40279.rds")
markers_start = grep("cg",colnames(df_gender))[1]
idx_clinicals = colnames(df_gender)[1:(markers_start-1)]
idx_cpg = colnames(df_gender)[markers_start:ncol(df_gender)]
idx_cpg = idx_cpg[idx_cpg %in% rownames(df_grim)]
df_gender = df_gender[,c(idx_clinicals,idx_cpg)]
saveRDS(df_gender, paste0("df_preproc_",gse,".rds"))

```

```{r gender predictions}

nbewasprobes = 10000
y_key = "gender"
rmarkdown::render('03_ewas.Rmd',output_file=paste0('03_ewas', nbewasprobes,'_',gse,'_',y_key, '.html'))

## Grid search and RF for gender pred 

df = mreadRDS(paste0("df_r0_ewas", nbewasprobes, "_", gse, ".rds"))
markers_start = grep("cg",colnames(df))[1]
idx_cpg = colnames(df)[markers_start:ncol(df)]
x <- df[,idx_cpg]
y <- df[,y_key]
dataset = cbind(x,y)

# control <- caret::trainControl(method='repeatedcv', 
                        number=10, 
                        repeats=3, 
                        search='grid')

#mtrycust = seq(0,200,20)
#mtrycust[1] = 1
#tunegrid <- expand.grid(.mtry = mtrycust) 

#rf_gridsearch <- caret::train(y ~ ., 
#                       data = dataset,
#                       method = 'rf',
#                       metric = 'Accuracy',
#                       tuneGrid = tunegrid)
#print(rf_gridsearch)





control <- trainControl(method='repeatedcv', 
                        number=10, 
                        repeats=3)
#Metric compare model is Accuracy
metric <- "Accuracy"
set.seed(123)
#Number randomely variable selected is mtry
mtry <- sqrt(ncol(x))
tunegrid <- expand.grid(.mtry=mtry)
rf_default_gender <- train(y~., 
                      data=dataset, 
                      method='rf', 
                      metric='Accuracy', 
                      tuneGrid=tunegrid, 
                      trControl=control)
print(rf_default_gender)
saveRDS(rf_default_gender,"rf_model_pred_gender.rds")

if(nrow(df_grim) > 100000){
	df_grim = t(df_grim)
}
gender =  predict(rf_default_gender, newdata = df_grim, nodes = TRUE)
names(gender) = colnames(df_grim)
saveRDS(gender,"pred_gender.rds")

```

# Combine predicitions in global sheet

```{r combine predictions}

ages = readRDS("pred_ages.rds")
disease = readRDS("pred_disease.rds")
family = readRDS("pred_family.rds")
super_f = readRDS("pred_super_f.rds")
classes = readxl::read_excel("classes_brain_tumor.xlsx") #supplemental file for dkfz with additionnal informations on meth_class
colnames(classes) = classes[1,]
classes = classes[-1,]
filter_classes = classes[,c(1,2,9,10)] # Conserve only interesting informations from meth_class
predictions = cbind.data.frame(ages,disease,family,super_f)
predictions[,"Sample_ID"] = rownames(predictions)
predictions = merge(predictions,filter_classes,by.x="disease",by.y = "Methylation Class Name Abbreviated")
Sample_ID = predictions$Sample_ID
predictions = predictions[,-7]
predictions = cbind.data.frame(Sample_ID,predictions)
WriteXLS::WriteXLS(predictions, "grimec_predictions.xlsx", verbose=TRUE, row.names=FALSE, AdjWidth=TRUE, BoldHeaderRow=TRUE, FreezeRow=1, FreezeCol=1)

```

# TSNE 

```{meth_class tsne}

gse = "trainGBMgrimec"
nbewasprobes = 10000
y_key = "meth_class"
rmarkdown::render('03_ewas.Rmd',output_file=paste0('03_ewas', nbewasprobes,'_',gse,'_',y_key, '.html'))

df = readRDS("df_r0_ewas10000_trainGBMgrimec.rds")
markers_start = grep("cg",colnames(df))[1]
idx_cpg = colnames(df)[markers_start:ncol(df)]
x <- df[,idx_cpg]
df_mc = df[,c(colnames(x),"meth_class")]
meth_class = readRDS("pred_disease.rds")
grim_tsne = df_grim[,colnames(df_grim) %in% colnames(x)]
grim_tsne = grim_tsne[,colnames(x)]
type = c(rep(1,nrow(x)),rep(2,nrow(grim_tsne)))
grim_tsne = cbind.data.frame(grim_tsne,meth_class)
df_mc = rbind.data.frame(df_mc,grim_tsne)
x=df_mc[,1:ncol(df_mc)-1]
tsne = Rtsne::Rtsne(x)
plot(tsne$Y,col=as.factor(df_mc$meth_class),pch=type)
legend("bottomleft", col=unique(as.factor(df_mc$meth_class)), legend=unique(df_mc$meth_class),pch=1,cex = 0.8)

```

```{meth_family tsne}

gse = "trainGBMgrimec"
nbewasprobes = 10000
y_key = "meth_family"
rmarkdown::render('03_ewas.Rmd',output_file=paste0('03_ewas', nbewasprobes,'_',gse,'_',y_key, '.html'))

df = readRDS("df_r0_ewas10000_trainGBMgrimec.rds")
markers_start = grep("cg",colnames(df))[1]
idx_cpg = colnames(df)[markers_start:ncol(df)]
x <- df[,idx_cpg]
df_mf = df[,c(colnames(x),"meth_family")]
meth_family = readRDS("pred_family.rds")
grim_tsne = df_grim[,colnames(df_grim) %in% colnames(x)]
grim_tsne = grim_tsne[,colnames(x)]
type = c(rep(1,nrow(x)),rep(2,nrow(grim_tsne)))
grim_tsne = cbind.data.frame(grim_tsne,meth_family)
df_sf = rbind.data.frame(df_mf,grim_tsne)
x=df_mf[,1:ncol(df_mf)-1]
tsne = Rtsne::Rtsne(x)
plot(tsne$Y,col=as.factor(df_mf$meth_family),pch=type)
legend("bottomleft", col=unique(as.factor(df_mf$meth_family)), legend=unique(df_mf$meth_family),pch=1,cex = 0.8)

```

```{super_family tsne}

gse = "trainGBMgrimec"
nbewasprobes = 10000
y_key = "super_family"
rmarkdown::render('03_ewas.Rmd',output_file=paste0('03_ewas', nbewasprobes,'_',gse,'_',y_key, '.html'))

df = readRDS("df_r0_ewas10000_trainGBMgrimec_super_family.rds")
markers_start = grep("cg",colnames(df))[1]
idx_cpg = colnames(df)[markers_start:ncol(df)]
x <- df[,idx_cpg]
df_sf = df[,c(colnames(x),"super_family")]
super_family = readRDS("pred_super_f.rds")
grim_tsne = df_grim[,colnames(df_grim) %in% colnames(x)]
grim_tsne = grim_tsne[,colnames(x)]
type = c(rep(1,nrow(x)),rep(2,nrow(grim_tsne)))
grim_tsne = cbind.data.frame(grim_tsne,super_family)
df_sf = rbind.data.frame(df_sf,grim_tsne)
x=df_sf[,1:ncol(df_sf)-1]
tsne = Rtsne::Rtsne(x)
plot(tsne$Y,col=as.factor(df_sf$super_family),pch=type)
legend("bottomleft", col=unique(as.factor(df_sf$super_family)), legend=unique(df_sf$super_family),pch=1,cex = 0.8)

```

# Compare to real age from grimec

```{r take and combine real age with prediction}

grim_cd = readRDS("../../datashare/GRIMEC001/real_grim.rds")
real_age = grim_cd$real_age
age = readRDS("pred_ages.rds")
age = cbind.data.frame(real_age,age)
rmse = sapply(age, function(x) { sqrt(mean((age$real_age - x)^2)) }) 
age = rbind.data.frame(age,rmse)
rownames(age)[nrow(age)] = "rmse"
saveRDS(age,"../../datashare/GRIMEC001/comp_real_age.rds")

```

```{r find big RMSE individuals}

age = readRDS("../../datashare/GRIMEC001/comp_real_age.rds")

age_self = age$Self[-nrow(age)]
names(age_self) = rownames(age)[-nrow(age)]
age_real = age$real_age[-nrow(age)]
names(age_real) = rownames(age)[-nrow(age)]

comp_age = age_self/age_real
plot(density(comp_age))
abline(v=mean(comp_age)-2*sd(comp_age))
abline(v=mean(comp_age)+2*sd(comp_age))

col = (comp_age<mean(comp_age)-sd(comp_age) | comp_age>mean(comp_age)+sd(comp_age))
name_col = names(col)
col = as.numeric(col)
names(col) = name_col
col = col+1

```

```{r check big RMSE individuals on tsne}

# Meth_class

gse = "trainGBMgrimec"
nbewasprobes = 10000
y_key = "meth_class"
rmarkdown::render('03_ewas.Rmd',output_file=paste0('03_ewas', nbewasprobes,'_',gse,'_',y_key, '.html'))

df = readRDS("df_r0_ewas10000_trainGBMgrimec.rds")
markers_start = grep("cg",colnames(df))[1]
idx_cpg = colnames(df)[markers_start:ncol(df)]
x <- df[,idx_cpg]
df_sf = df[,c(colnames(x),"meth_class")]
meth_class = readRDS("pred_disease.rds")
grim_tsne = df_grim[,colnames(df_grim) %in% colnames(x)]
grim_tsne = grim_tsne[,colnames(x)]
type = c(rep(1,nrow(x)),col)
grim_tsne = cbind.data.frame(grim_tsne,meth_class)
df_sf = rbind.data.frame(df_sf,grim_tsne)
x=df_sf[,1:ncol(df_sf)-1]
tsne = Rtsne::Rtsne(x)
plot(tsne$Y,col=as.factor(df_sf$meth_class),pch=type)
legend("bottomleft", col=unique(as.factor(df_sf$meth_class)), legend=unique(df_sf$meth_class),pch=1,cex = 0.8)

# Meth_family

gse = "trainGBMgrimec"
nbewasprobes = 10000
y_key = "meth_family"
rmarkdown::render('03_ewas.Rmd',output_file=paste0('03_ewas', nbewasprobes,'_',gse,'_',y_key, '.html'))

df = readRDS("df_r0_ewas10000_trainGBMgrimec.rds")
markers_start = grep("cg",colnames(df))[1]
idx_cpg = colnames(df)[markers_start:ncol(df)]
x <- df[,idx_cpg]
df_sf = df[,c(colnames(x),"meth_family")]
meth_family = readRDS("pred_family.rds")
grim_tsne = df_grim[,colnames(df_grim) %in% colnames(x)]
grim_tsne = grim_tsne[,colnames(x)]
type = c(rep(1,nrow(x)),col)
grim_tsne = cbind.data.frame(grim_tsne,meth_family)
df_sf = rbind.data.frame(df_sf,grim_tsne)
x=df_sf[,1:ncol(df_sf)-1]
tsne = Rtsne::Rtsne(x)
plot(tsne$Y,col=as.factor(df_sf$meth_family),pch=type)
legend("bottomleft", col=unique(as.factor(df_sf$meth_family)), legend=unique(df_sf$meth_family),pch=1,cex = 0.8)

# Super_family

gse = "trainGBMgrimec"
nbewasprobes = 10000
y_key = "super_family"
rmarkdown::render('03_ewas.Rmd',output_file=paste0('03_ewas', nbewasprobes,'_',gse,'_',y_key, '.html'))

df = readRDS("df_r0_ewas10000_trainGBMgrimec.rds")
markers_start = grep("cg",colnames(df))[1]
idx_cpg = colnames(df)[markers_start:ncol(df)]
x <- df[,idx_cpg]
df_sf = df[,c(colnames(x),"super_family")]
super_family = readRDS("pred_super_f.rds")
grim_tsne = df_grim[,colnames(df_grim) %in% colnames(x)]
grim_tsne = grim_tsne[,colnames(x)]
type = c(rep(1,nrow(x)),col)
grim_tsne = cbind.data.frame(grim_tsne,super_family)
df_sf = rbind.data.frame(df_sf,grim_tsne)
x=df_sf[,1:ncol(df_sf)-1]
tsne = Rtsne::Rtsne(x)
plot(tsne$Y,col=as.factor(df_sf$super_family),pch=type)
legend("bottomleft", col=unique(as.factor(df_sf$super_family)), legend=unique(df_sf$super_family),pch=1,cex = 0.8)

```

# Comparison DMR LGG and clock probes

```{r study creation}

study = readRDS("../../datashare/GSE90496/study_GSE90496.rds")
study$exp_grp$LGG_yes = study$exp_grp["methylation class:ch1"]=="LGG, PA/GG ST"
study$exp_grp$LGG_yes = as.factor(study$exp_grp$LGG_yes)

split = strsplit(study$exp_grp[,"methylation class:ch1"],",")
split = sapply(split,"[[",1)
study$exp_grp$meth_family = split
study$exp_grp$LGG_gl_yes = study$exp_grp["meth_family"]=="LGG"
study$exp_grp$LGG_gl_yes = as.factor(study$exp_grp$LGG_gl_yes)

saveRDS(study,"../../datashare/trainGBMgrimec/study_trainGBMgrimec.rds")

```

```{r LGG specific DMR comparison}

model_formula = "meth~LGG_yes"; study_filename = "study_trainGBMgrimec.rds"; rmarkdown::render("../../ewascombpr/vignettes/02_ewas_combp.Rmd",output_file = "02_ewas_combp_LGG_30.html")

LGG = readxl::read_excel("../../ewascombpr/vignettes/global_results_study_trainGBMgrimec.rds_modelcalllm_meth~LGG_yes_1e-30.xlsx")
LGG_probes = strsplit(LGG$probes,";")
LGG_probes = unlist(LGG_probes)

probes_clock = betas[[2]]$coeff$probes

dmr_clock_30 =  intersect(probes_clock,LGG_probes)
length(dmr_clock_30)

model_formula = "meth~LGG_yes"; pval_thresh = 1e-05; study_filename = "study_trainGBMgrimec.rds"; rmarkdown::render("../../ewascombpr/vignettes/02_ewas_combp.Rmd",output_file = "02_ewas_combp_LGG_05.html")

LGG_5 = readxl::read_excel("../../ewascombpr/vignettes/global_results_study_trainGBMgrimec.rds_modelcalllm_meth~LGG_yes_1e-05.xlsx")
LGG_5_probes = strsplit(LGG_5$probes,";")
LGG_5_probes = unlist(LGG_5_probes)

dmr_clock_5 =  intersect(probes_clock,LGG_5_probes)
length(dmr_clock_5)

```

```{r LGG global DMR comparison}

# pval 30

model_formula = "meth~LGG_gl_yes"; study_filename = "study_trainGBMgrimec.rds"; pval_thresh = 1e-30; rmarkdown::render("../../ewascombpr/vignettes/02_ewas_combp.Rmd",output_file = "02_ewas_combp_LGG_gl_30.html")

LGG_gl_30 = readxl::read_excel("../../ewascombpr/vignettes/global_results_study_trainGBMgrimec.rds_modelcalllm_meth~LGG_gl_yes_1e-30.xlsx")
LGG_gl_30_probes = strsplit(LGG_gl_30$probes,";")
LGG_gl_30_probes = unlist(LGG_gl_30_probes)

dmr_clock_gl_30 = intersect(probes_clock,LGG_gl_30_probes)
length(dmr_clock_gl_30)

# pval 80

model_formula = "meth~LGG_gl_yes"; study_filename = "study_trainGBMgrimec.rds"; pval_thresh = 1e-80; rmarkdown::render("../../ewascombpr/vignettes/02_ewas_combp.Rmd",output_file = "02_ewas_combp_LGG_gl_80.html")

LGG_gl_80 = readxl::read_excel("../../ewascombpr/vignettes/global_results_study_trainGBMgrimec.rds_modelcalllm_meth~LGG_gl_yes_1e-80.xlsx")
LGG_gl_80_probes = strsplit(LGG_gl_80$probes,";")
LGG_gl_80_probes = unlist(LGG_gl_80_probes)

dmr_clock_gl_80 = intersect(probes_clock,LGG_gl_80_probes)
length(dmr_clock_gl_80)

# pval 100

model_formula = "meth~LGG_gl_yes"; study_filename = "study_trainGBMgrimec.rds"; pval_thresh = 1e-100; rmarkdown::render("../../ewascombpr/vignettes/02_ewas_combp.Rmd",output_file = "02_ewas_combp_LGG_gl_100.html")

LGG_gl_100 = readxl::read_excel("../../ewascombpr/vignettes/global_results_study_trainGBMgrimec.rds_modelcalllm_meth~LGG_gl_yes_1e-100.xlsx")
LGG_gl_100_probes = strsplit(LGG_gl_100$probes,";")
LGG_gl_100_probes = unlist(LGG_gl_100_probes)

dmr_clock_gl_100 = intersect(probes_clock,LGG_gl_100_probes)
length(dmr_clock_gl_100)

# pval 120

model_formula = "meth~LGG_gl_yes"; study_filename = "study_trainGBMgrimec.rds"; pval_thresh = 1e-120; rmarkdown::render("../../ewascombpr/vignettes/02_ewas_combp.Rmd",output_file = "02_ewas_combp_LGG_gl_120.html")

LGG_gl_120 = readxl::read_excel("../../ewascombpr/vignettes/global_results_study_trainGBMgrimec.rds_modelcalllm_meth~LGG_gl_yes_1e-120.xlsx")
LGG_gl_120_probes = strsplit(LGG_gl_120$probes,";")
LGG_gl_120_probes = unlist(LGG_gl_120_probes)

dmr_clock_gl_120 = intersect(probes_clock,LGG_gl_120_probes)
length(dmr_clock_gl_120)

# pval 150

model_formula = "meth~LGG_gl_yes"; study_filename = "study_trainGBMgrimec.rds"; pval_thresh = 1e-150; rmarkdown::render("../../ewascombpr/vignettes/02_ewas_combp.Rmd",output_file = "02_ewas_combp_LGG_gl_150.html")

LGG_gl_150 = readxl::read_excel("../../ewascombpr/vignettes/global_results_study_trainGBMgrimec.rds_modelcalllm_meth~LGG_gl_yes_1e-150.xlsx")
LGG_gl_150_probes = strsplit(LGG_gl_150$probes,";")
LGG_gl_150_probes = unlist(LGG_gl_150_probes)

dmr_clock_gl_150 = intersect(probes_clock,LGG_gl_150_probes)
length(dmr_clock_gl_150)

```

