---
title: "Sensitivity Analysis"
author: "Fabien Jossaud, Florent Chuffart"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---


```{r echo=FALSE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=10, fig.height=5, eval=TRUE, echo=FALSE, results="hide", show.warnings=FALSE)
source("common.R")
source("sa_params.R")
options(scipen=999)
```

```{r}
stats = lapply(gses, function(gse) { 
  results = lapply(ns, function(n) {
    results = lapply(ps, function(p) {
      results = lapply(seeds, function(seed) {
        results_file = paste0("results_gse", gse, "n", n, "seed", seed, "p", p,".rds")
        if (file.exists(results_file)) {
          results = mreadRDS(results_file)
          results = as.list(results)
          results$n    = n    
          results$p    = p    
          results$seed = seed 
          results$gse  = gse  
          return(results)
        } else {
          NULL
        }
      })
      results = do.call(rbind, results)
      results = as.data.frame(results)
      results = data.frame(lapply(data.frame(results, stringsAsFactors=FALSE), unlist), stringsAsFactors=FALSE)
      return(results)
    })
    results = do.call(rbind, results)
    results = as.data.frame(results)
    results = data.frame(lapply(data.frame(results, stringsAsFactors=FALSE), unlist), stringsAsFactors=FALSE)
    return(results)
  })
  results = do.call(rbind, results)
  results = as.data.frame(results)
  results = data.frame(lapply(data.frame(results, stringsAsFactors=FALSE), unlist), stringsAsFactors=FALSE)
  return(results)
})
stats = do.call(rbind, stats)
stats = as.data.frame(stats)
stats = data.frame(lapply(data.frame(stats, stringsAsFactors=FALSE), unlist), stringsAsFactors=FALSE)



# gse="GSE40279"
# n=200
# p=300000
# seed=2
#
# results_file = paste0("results_gse", gse, "n", n, "seed", seed, "p", p,".rds")
# results = mreadRDS(results_file)
# results = as.list(results)
# results$n    = n
# results$p    = p
# results$seed = seed
# results$gse  = gse
# results$nbmod1_probes








for (i in c(1:3, 14, 15, 1:17)){
  layout(matrix(1:length(gses), 1), respect=TRUE)
  for(gse in gses){ 
  
    # plot(0, 0, col=0, xlab="p", ylab= names_res[3], main=paste0(gse), xlim=range(results_g$p), ylim=c(0, max(results_g$up)))
    # ns = unique(results_g$n)
    # foo = lapply(ns, function(n) {
    #   results = results_g[results_g$n==n,]
    #   tmp_col = which(n==ns)
    #   lines(results$p, results$var, col=tmp_col, lty=1, type = "b")
    #   arrows(x0=results$p, y0=results$lo, x1=results$p, y1=results$up, code=3, angle=90, length = 0.03, col=tmp_col, lwd=2)
    # })
    # legend(x="bottomleft", legend=ns, fill=1:length(ns), title="n")
    
    ylab = colnames(stats)[i]
    formula = as.formula(paste0(ylab, "~n+p"))
    boxplot(formula, stats[stats$gse==gse,], col=1:length(ns), las=2, main=gse, ylab=ylab)
    # legend(x="bottomleft", legend=ns, fill=1:length(ns), title="n")
  }
}


# m = lm(exec_time~n+p+gse, stats)
# summary(m)
# anova(m)

# m = lm(rmsemod2_test~n+p+gse, stats)
# summary(m)
# anova(m)


stats$time = stats$exec_time / 60
stats$RMSE_test = stats$rmsemod2_test
stats$nb_probes = stats$nbmod2_probes
stats$nb_probes = stats$nbmod1_probes



```










# res

```{r, fig.height=7, fig.width=7}
sum(stats$exec_time) / 60 / 60
# Note cette experience reprsnete 85 heures de calcul


layout(matrix(1:4, 2, byrow=TRUE), respect=TRUE)
for(gse in gses){ 
  formula = as.formula(paste0("time", "~n+p"))
  foo = boxplot(formula, stats[stats$gse==gse,], col=1:length(ns), las=2, main=gse, ylab="time (min.)", xaxt="n", xlab="p")
  axis(1, at=2+(round(1:(length(foo$names)/4))-1)*4, label=unique(substr(foo$names, 5, 100)), las=2)
  legend(x="topleft", legend=ns, fill=1:length(ns), title="n")
}
sum(stats$exec_time) / 60 / 60
# Note cette experience reprsnete 85 heures de calcul
# le temps d'execution explose avec p. en effet x est en en echelle log et malgré cela exec_time augmente de facon "exponetielle".



for(gse in gses){ 
  formula = as.formula(paste0("RMSE_test", "~n+p"))
  boxplot(formula, stats[stats$gse==gse,], col=1:length(ns), las=2, main=gse, ylab="RMSE (test)", xaxt="n", xlab="p", ylim=c(3,10))
  axis(1, at=2+(round(1:(length(foo$names)/4))-1)*4, label=unique(substr(foo$names, 5, 100)), las=2)
  # legend(x="bottomleft", legend=ns, fill=1:length(ns), title="n")
}
# La performance de notre horloge augemte de facon logarithmique avec p(x en echelle log). 
# Les gains de performance deviennet de plus en plus couteux en terme de p.






for(gse in gses){ 
  formula = as.formula(paste0("nbmod2_probes", "~n+p"))
  boxplot(formula, stats[stats$gse==gse,], col=1:length(ns), las=2)
  # legend(x="topleft", legend=ns, fill=1:length(ns), title="n")
}
# problem, nbmod2_probes trop grand, probleme avec x_optim

layout(matrix(1:length(gses), 1), respect=TRUE)
for(gse in gses){ 
  formula = as.formula(paste0("nbmod1_probes", "~n+p"))
  boxplot(formula, stats[stats$gse==gse,], col=1:length(ns), las=2, main=gse)
  legend(x="topleft", legend=ns, fill=1:length(ns), title="n")
} 
# problem, nbmod1_probes <= nb_train !! 








# for (i in 1:17){
#   layout(matrix(1:3, 1), respect=TRUE)
#   plot(0, 0, col=0, xlab="p", ylab= names_res[3], main=paste0(gse), xlim=range(results_g$p), ylim=c(0, max(results_g$up)))
#   ns = unique(results_g$n)
#   foo = lapply(ns, function(n) {
#     results = results_g[results_g$n==n,]
#     tmp_col = which(n==ns)
#     lines(results$p, results$var, col=tmp_col, lty=1, type = "b")
#     arrows(x0=results$p, y0=results$lo, x1=results$p, y1=results$up, code=3, angle=90, length = 0.03, col=tmp_col, lwd=2)
#   })
#   legend(x="bottomleft", legend=ns, fill=1:length(ns), title="n")
#
# }

```
