---
title: "Build Illumina methylation study"
author: "Florent Chuffart"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---


```{r echo=FALSE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=FALSE, results="hide")
source("common.R")
```

```{r batch, eval=FALSE, echo=FALSE}
gses = c( 
  "GSE20067", # 27k Genome wide DNA methylation profiling of diabetic nephropathy in type 1 diabetes mellitus
  "GSE41037", # 27k Genome wide DNA methylation profiling of whole blood in schizophrenia patients and healthy subjects.
  # "GSE40279", # 450k Hannum 2013
  # "GSE41169",
  # "GSE20236",
  # "GSE19711",
  # "GSE19711",
  # "GSE42861", # ***
  # "GSE111223",
  # "GSE34035",
  # "GSE28746",
  # "GSE34035",
  # # "GSE120610",
  # "GSE159899",
  # "GSE145254"
  # "GSE179759"
  NULL
)
for (gse in gses) {
  ls()
  rm(list = ls()[-which(ls()=="gse")])
  ls()
  print(paste0("************ ", gse, " ************"))
  s_filename = paste0("study_", gse, ".rds")
  source(paste0("params_", gse, ".R"))
  rmarkdown::render("01_build_study_generic.Rmd", output_file=paste0("01_build_study_", gse, ".html"))    
  rmarkdown::render("02_stats_desc.Rmd", output_file=paste0("02_stats_desc_", gse, ".html"))    
  rmarkdown::render("03_preproc.Rmd", output_file=paste0("03_preproc_", gse, ".html"))    
  # rmarkdown::render("04_model.Rmd", output_file=paste0("04_model_", gse, ".html"))
  # rmarkdown::render("05_evaluation.Rmd", output_file=paste0("05_evaluation_", gse, ".html"))
}
```


```{r params}
source("params_default.R")
```


# Purpose

This vignette 

- build
- check
- save 

methylation study for `r gse`.

```{r, echo=FALSE, eval=TRUE}
# Build
s_filename = paste0("study_", gse, ".rds")
print(paste0("#####", gse))
s_tmp = epimedtools::create_study()
s_tmp$gse = gse
foo = s_tmp$get_data(dest_dir="~/projects/datashare")
dim(foo)
s = epimedtools::create_study()
# data
s$data = foo
# exp_grp from epimed_DB
url = paste0("http://epimed.univ-grenoble-alpes.fr/database/parameters/",gse)
df1 = read.csv2(url, header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".", na.strings="", row.names=1)
s$exp_grp = df1
if (s_tmp$platform_name=="GPL8490") {
  print("27k")
  library(IlluminaHumanMethylation27kanno.ilmn12.hg19)
  pf27k = data.frame(getAnnotation(IlluminaHumanMethylation27kanno.ilmn12.hg19))
  s$platform = pf27k
} else if (s_tmp$platform_name=="GPL13534") {
  print("450k")
  library(IlluminaHumanMethylation450kanno.ilmn12.hg19)
  pf450k = data.frame(getAnnotation(IlluminaHumanMethylation450kanno.ilmn12.hg19))
  s$platform = pf450k  
} else if (s_tmp$platform_name=="GPL23976") {
  print("epic")
  library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)  
  pfepic = data.frame(getAnnotation(IlluminaHumanMethylationEPICanno.ilm10b4.hg19))
  s$platform = pfepic  
} else {
  stop(paste0("platform problem ", gse))
}

# Check
dim(s$data)
dim(s$exp_grp)
s$data = s$data[,!colnames(s$data)%in%sample_blacklist]
s$exp_grp = s$exp_grp[!rownames(s$exp_grp)%in%sample_blacklist,]
dim(s$data)
dim(s$exp_grp)
if (sum(!rownames(s$exp_grp) %in% colnames(s$data)) !=0 ) {stop(paste0("problem exp_grp names ", gse))}
s$exp_grp = s$exp_grp[colnames(s$data),]
if (sum(rownames(s$exp_grp) != colnames(s$data)) !=0 ) {stop(paste0("problem exp_grp names ", gse))}

dim(s$platform)
dim(s$data)
if (sum(!rownames(s$data) %in% rownames(s$platform)) !=0 ) {warning(paste0("problem pf names ", gse))}
s$platform = s$platform[intersect(rownames(s$data), rownames(s$platform)),]
s$data = s$data[rownames(s$platform),]
if (sum(rownames(s$data) != rownames(s$platform)) !=0 ) {stop(paste0("problem pf names ", gse))}

# covariates
for (cov in covariates) {
  if (is.character(s$exp_grp[[cov]])) {
    s$exp_grp[[cov]] = as.factor(s$exp_grp[[cov]])
  }
}

```{r results="verbatim"}
# Save
print(paste0("Writing ", s_filename, "..."))
s$save(s_filename)
df = cbind(s$exp_grp, t(s$data[,rownames(s$exp_grp)]))

df_filename = paste0("df_", gse, ".rds")
print(paste0("Writing ", df_filename, "..."))
saveRDS(df, df_filename)
```

# Session Information

```{r, results="verbatim"}
sessionInfo()
```

