---
title: "Re-build Illumina methylation study with only 27k probes"
author: "Florent Chuffart"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---


```{r echo=FALSE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=FALSE, results="hide")
source("common.R")
```

```{r params}
source("params_default.R")
```


```{r loading_data}
df_filename = paste0("df_", gse, ".rds")
df = mreadRDS(df_filename)
dim(df)
```


```{r building_indexes}
idx_samples = rownames(df)
markers_start = grep("cg",colnames(df))[1]
idx_clinicals = colnames(df)[1:(markers_start-1)]
idx_cpg = colnames(df)[markers_start:ncol(df)]
```




```{r, echo=FALSE, eval=TRUE}
library(IlluminaHumanMethylation27kanno.ilmn12.hg19)
pf27k = data.frame(getAnnotation(IlluminaHumanMethylation27kanno.ilmn12.hg19))

probes27k = intersect(idx_cpg, rownames(pf27k))

df = df[,c(idx_clinicals, probes27k)]
df_filename = paste0("df_27k", gse, ".rds")
print(paste0("Writing ", df_filename, "..."))
saveRDS(df, df_filename)
dim(df)
```

# Session Information

```{r, results="verbatim"}
sessionInfo()
```

