---
title: "Descriptive Statistics"
author: "Fabien Jossaud, Florent Chuffart"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---


```{r include=FALSE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=TRUE, results="verbatim")
```

```{r data}

if (!exists("mreadRDS")) { mreadRDS = memoise::memoise(readRDS) }
if (!exists("df_GSE40279")) {
  df_GSE40279 = mreadRDS("df_GSE40279.rds")  
}
df = df_GSE40279

# Index

idx_samples = rownames(df)
idx_clinicals = colnames(df)[1:7]
idx_cpg = colnames(df)[8:ncol(df)]


```

```{r Age distribution}

par(mfrow = c(1,1))
AgeD = hist(df$age__y_, breaks=20, col="red",prob =TRUE, ylim = c(0,0.035)) 
DA = density(df$age__y_)
lines(DA$x,DA$y)
Norm_Age = shapiro.test(df$age__y_)
text(60,0.03, paste0("SW Normality test p-val = ", round(Norm_Age$p.value,5)))

mean
sd
smirnoff
signif(2)

```

```{r Gender}

idx_g = colnames(df)[5]

dist_g = table(df$gender)  
bar_g = barplot(dist_g,col = c("pink","blue"), ylim = c(0,nrow(df)*0.7))
text(bar_g, dist_g + nrow(df)*0.02, labels = dist_g)

AfG = aggregate(formula(paste0("age__y_~",idx_g)),data=df,mean)
bar_AfG = barplot(height = AfG$age__y_ , names = AfG$gender, col=c("pink","blue"), ylim = c(0,100))
text(bar_AfG, AfG$age__y_ + 2, labels = AfG$age__y_)
Age_H = df$age__y_[which(df$gender == "M")]
Age_F = df$age__y_[which(df$gender == "F")]
WTG = wilcox.test(Age_F,Age_H)
text(x = 1, y = 80, labels = paste0("Wilcoxon p-val =", WTG$p.value))

beanplot::beanplot(age__y_~gender,data=df,col = c("blue","red"),method="jitter")
text(x = 1.5, y = 110, labels = paste0("Wilcoxon p-val =", WTG$p.value))

boxplot(age__y_~gender,data=df)
text(x = 1.5, y = 90, labels = paste0("Wilcoxon p-val =", WTG$p.value))

# First style 

par(mfrow = c(1,2))

hist(Age_H, breaks=20, col = "blue", prob = TRUE)
DAH = density(Age_H)
lines(DAH$x, DAH$y)

hist(Age_F, breaks=20, col = "pink", prob = TRUE)
DAF = density(Age_F)
lines(DAF$x, DAF$y)

```

```{r Ethnicity}

idx_e = colnames(df)[6]
dist_e = table(df[,idx_e])
AfE = aggregate(age__y_~ethnicity,data=df,mean)

# Barplot Age distribution by ethnicity

bar_e = barplot(dist_e,col = c("blue","red"), ylim = c(0,nrow(df)))
text(bar_e, dist_e + nrow(df)*0.02, labels = dist_e)

# Barplot Age mean by ethnicity

bar_AfE = barplot(height = AfE$age__y_ , names = AfE$ethnicity, col=c("blue","red"), ylim = c(0,100))
text(bar_AfE, AfE$age__y_ + 4, labels = AfE$age__y_)

# Age Distribution by ethnicity

Age_Eu = df$age__y_[which(df[,idx_e] == "Caucasian - European")]
Age_Hi = df$age__y_[which(df[,idx_e] == "Hispanic - Mexican")]

# Test Wilcoxon 

WTE = wilcox.test(Age_Eu,Age_Hi)

# Beanplot 

beanplot::beanplot(age__y_~ethnicity,data=df,col = c("blue","red"),method="jitter")
text(x = 1.5, y = 110, labels = paste0("Wilcoxon p-val =", WTE$p.value))

# Boxplot

boxplot(age__y_~ethnicity,data=df,col = c("blue","red"))
text(x = 1.5, y = 90, labels = paste0("Wilcoxon p-val =", WTE$p.value))

# Hist

par(mfrow = c(1,2))

hist(Age_Hi, breaks=20, col = "red", prob = TRUE)
DAHi = density(Age_Hi)
lines(DAHi$x, DAHi$y)

hist(Age_Eu, breaks=20, col = "blue", prob = TRUE)
DAEu = density(Age_Eu)
lines(DAEu$x, DAEu$y) 


```

# Session Information

```{r, results="verbatim"}
sessionInfo()
```

