---
title: "Model evaluation (comparison with Horvath and Hannum)"
author: "Fabien Jossaud, Florent Chuffart"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---


```{r echo=FALSE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=TRUE, results="verbatim")
source("common.R")
```

```{r params}
source("params_default.R")
```

# Prerequisits

We need to execute 03_preproc to have our df preprocess. 
We need to execute 04_modelpreproc to have ...

```{r building_indexes}
idx_samples = rownames(df)
markers_start = grep("cg",colnames(df))[1]
idx_clinicals = colnames(df)[1:(markers_start-1)]
idx_cpg = colnames(df)[markers_start:ncol(df)]
```

# Define train and test samples

```{r train test sets}
Ntrain = floor(nrow(df)/2)
set.seed(1)
idx_train = sample(rownames(df), Ntrain)
idx_test = setdiff(rownames(df), idx_train)

tmp_mat_cpg = as.matrix(df[,idx_cpg])
# head(tmp_mat_cpg)
Xtrain = tmp_mat_cpg[idx_train,]
Ytrain = df[idx_train,y_key]
Xtest = tmp_mat_cpg[idx_test,]
Ytest = df[idx_test,y_key]
``` 


# Call data (Need to be modified to generalize and make it at a variable)

 
```{r methylclock_models}

layout(matrix(1:2,1),respect = TRUE)

if (!exists("mmethylclock_DNAmAge")) {mmethylclock_DNAmAge = memoise::memoise(methylclock::DNAmAge)}
modelHOTr = mmethylclock_DNAmAge(t(Xtrain), age=Ytrain, cell.count=FALSE, clocks="Hannum")
modelHO = mmethylclock_DNAmAge(t(Xtest),age=Ytest,cell.count = FALSE, clocks = "Hannum")

if(sum(is.na(modelHOTr$Hannum)) == 0){
  rmseHOTr = signif(sqrt(mean((modelHOTr$age - modelHOTr$Hannum)^2)),3)
  rmseHO = signif(sqrt(mean((modelHO$age - modelHO$Hannum)^2)),3)
	
	plot(modelHOTr$Hannum, modelHOTr$age, xlab="Methylomic Age", ylab="Chronological Age", main=paste0("Pred with Hannum Method on Train Set, rmse = ",rmseHOTr))
	plot(modelHO$Hannum, modelHO$age, xlab="Methylomic Age", ylab="Chronological Age", main=paste0("Pred with Hannum Method on Test Set, rmse = ",rmseHO))

} else{
	rmseHOTr = NA
	rmseHO = NA
}

modelHOrTr = mmethylclock_DNAmAge(t(Xtrain),age=Ytrain,cell.count = FALSE, clocks = "Horvath")
modelHOr = mmethylclock_DNAmAge(t(Xtest),age=Ytest,cell.count = FALSE, clocks = "Horvath")
	
if(sum(is.na(modelHOrTr$Horvath)) == 0){
		rmseHOrTr = signif(sqrt(mean((modelHOrTr$age - modelHOrTr$Horvath)^2)),3)
	rmseHOr = signif(sqrt(mean((modelHOr$age - modelHOr$Horvath)^2)),3)

	plot(modelHOrTr$Horvath, modelHOrTr$age, xlab="Methylomic Age", ylab="Chronological Age", main=paste0("Pred with Horvath Method on Train Set, rmse = ",rmseHOrTr))
	plot(modelHOr$Horvath, modelHOr$age, xlab="Methylomic Age", ylab="Chronological Age", main=paste0("Pred with Horvath Method on Test Set, rmse = ",rmseHOr))
} else{
	rmseHOrTr = NA
	rmseHOr = NA
}

```

```{r methylclock_results}
colnames.rmse = c()
rmse_Tr = c()
rmse_Te = c()
for (i in 1:length(rmse_pred)){ 
	rmse_Tr = c(rmse_Tr, rmse_pred[[i]]$rmseTr)
	rmse_Te = c(rmse_Te, rmse_pred[[i]]$rmseTe)
	colnames.rmse = c(colnames.rmse, paste0("Regression alpha = ",alphas[1]))
}
rmse_Tr = c(rmse_Tr, rmseHOTr, rmseHOrTr)
rmse_Te = c(rmse_Te, rmseHO, rmseHOr)
colnames.rmse = c(colnames.rmse, "Hannum method", "Horvath method")
rownames.rmse = c("Train Set", "Test Set")

rmse_compar = as.data.frame(rbind(rmse_Tr,rmse_Te))
colnames(rmse_compar) = colnames.rmse
rownames(rmse_compar) = rownames.rmse

rmse_compar

```


# Session Information

```{r, results="verbatim"}
sessionInfo()
```
