---
title: "Code Hannum 2013"
---
title: "Descriptive Statistics"
author: "Fabien Jossaud, Florent Chuffart"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---


```{r include=FALSE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=TRUE, results="verbatim")
```


## Appel data ( à modifier pour généraliser)

```{r appel data}
if (!exists("mreadRDS")) { mreadRDS = memoise::memoise(readRDS) }
df = mreadRDS("df_GSE40279.rds")
```



## Trouver valeurs manquantes 

```{r valeurs manquantes}

# On compte le pourcentage de valeurs manquantes

# apply_func = epimedtools::monitored_apply
# foo = apply_func(mod=1, df, 1, function(x) {sum(is.na(x))})


apply_func = apply
pctNArow = apply_func(df, 1, function(x) sum(is.na(x))) / ncol(df) * 100 # Par ligne

pctNAcol = apply(df,2,function(x) sum(is.na(x))) / nrow(df) * 100 # Par colonne

# On regarde lesquelles sont supérieures à 20% de données manquantes 

suppr = which(pctNArow > 20) # Lignes

suppc = which(pctNAcol > 20) # Colonnes

# On supprime les lignes et les colonnes correspondantes

dsupp = df[-(suppr),-(suppc)]

print(paste0("Nombre de lignes supprimées : ",length(suppr)))

print(paste0("Nombre de colonnes supprimées : ",length(suppc)))
```



# Session Information

```{r, results="verbatim"}
sessionInfo()
```

